config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'events#index' 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  resources :users, only: [:show]
  resources :contact_forms, only: [:create]
  resources :contact_organizers, only: [:create, :new]
  resources :report_issues, only: [:create, :new]
  resources :email_events, only: [:create, :new]
  resources :report_events, only: [:create, :new]
  resources :shared_events, only: [:index]
  resources :events
  resources :saved_events, only: [:create, :destroy, :index]
  get 'contact_us', to: 'contact_forms#new'
  get 'autocomplete', to: 'events#autocomplete'
  get 'howitworks' => 'static_pages#howitworks'
  get 'terms' => 'static_pages#terms'
end

app/controllers/shared_events_controller.rb
class SharedEventsController < ApplicationController
	before_action :authenticate_user!

	def index
		if params[:search]
      @shared_events = Event.shared_search(params[:search]).where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per_page(15)
    else
      @shared_events = Event.where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per_page(15)
    end
	end
end

app/views/shared_events/index.html.erb
<% title "Shared Events" %>

<h3 class="page-heading">Shared Events</h3>

<%= form_tag(shared_events_path, :method => "get") do %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], class: "form-control shared-events-search-input", placeholder: "Search by title" %>
    <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
         of using a Rails form helper -->
    <div class="shared-search-clear-wrapper">
	    <button class="btn btn-default btn-default-primary-text btn-search-shared" type="submit">Search</button>
	    &nbsp;
	    <%= link_to "Clear", shared_events_path, class: "btn btn-default btn-default-primary-text btn-search-shared" %>
	  </div>
  </div>
<% end %>

<div class="shared-events-results">
	<% if @shared_events.any? %>
		<% if params[:search].present? %>
			<p><%= pluralize(@shared_events.count, "result") %> found.</p>
		<% end %>
		<% @shared_events.each do |shared_event| %>
			<p>
				<div>
					<span>
						<%= shared_event.title %>
					</span>
					<span class="brand-fun"> | </span>
					<span>
						<%= pluralize(SavedEvent.where(event_id: shared_event.id).count, 'save') %>
					</span>
					<span class="brand-fun"> | </span>
					<span>
						<%= pluralize(shared_event.impressionist_count(:filter => :session_hash), 'view') %>
					</span>
				</div>
				<span><%= link_to "View", event_path(shared_event) %></span> |
				<span><%= link_to "Edit", edit_event_path(shared_event), rel: "nofollow" %></span> |
				<span><%= link_to "Delete", event_path(shared_event), method: :delete, data: { confirm: "Are you sure you want to delete '#{shared_event.title}'?" }  %></span>
			</p>
		<% end %>
	<% else %>
		<% if params[:search].present? %>
			<p>0 results found for '<%= params[:search] %>'</p>
		<% else %>
			<p>All the events you <%= link_to "share", new_event_path() %> will be listed here for easy management.</p>
		<% end %>
	<% end %>
</div>


<%= will_paginate @shared_events, renderer: BootstrapPagination::Rails %>