config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'events#index' 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  resources :users, only: [:show]
  resources :contact_forms, only: [:create]
  resources :contact_organizers, only: [:create, :new]
  resources :report_issues, only: [:create, :new]
  resources :email_events, only: [:create, :new]
  resources :report_events, only: [:create, :new]
  resources :shared_events, only: [:index]
  resources :events
  resources :saved_events, only: [:create, :destroy, :index]
  get 'contact_us', to: 'contact_forms#new'
  get 'autocomplete', to: 'events#autocomplete'
  get 'howitworks' => 'static_pages#howitworks'
  get 'terms' => 'static_pages#terms'
end

app/models/user.rb
class User < ActiveRecord::Base
  # extend FriendlyId
  # friendly_id :name, use: :slugged
  
  # will obfuscate event ids (upto 10 billion different possibilities)
  # NB: obfuscate_id messes up tests when looking up a fixture in test db as that process does not use find
  # and as a result does not deobfuscate
  # unless Rails.env.test?
  #   obfuscate_id spin: 34658291
  # end

  # Include default devise modules. Others available are:
  # :lockable and :timeoutable

  devise :database_authenticatable, :registerable,
   :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]

  validates :name, presence: true, uniqueness: true
  validates :facebook_url, format: /\A((http|https):\/\/)?(?:www.)?facebook.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[?\w\-]*\/)?(?:profile.php\?id=(?=\d.*))?([\w\-]*)?/, allow_blank: true
  validates :twitter_handle, format: /\A(\w){1,15}\z/, allow_blank: true

  has_many :events, dependent: :destroy
	has_many :saved_events, dependent: :destroy
  belongs_to :location

  # this method is called by devise to check for "active" state of the model i.e. whether a user is active or disabled.
  def active_for_authentication?
    super && self.is_active?
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.skip_confirmation!
      user.save!
    end
  end
end

app/views/shared/_calendar_buttons.html.erb
<%# saved_event_ids = SavedEvent.pluck(:event_id) %>

<%# if saved_event_ids.include? event.id %>
	<%# saved_count = saved_event_ids.count(event.id) %>
	<%# if saved_count >= 1000000 %>
		<%# saved_count_string = (saved_count/1000000.0).round(2).to_s + "M" %>
	<%# elsif saved_count >= 100000 %>
		<%# saved_count_string = (saved_count/1000.0).round(0).to_s + "K" %>
	<%# elsif saved_count >= 10000 %>
		<%# saved_count_string = (saved_count/1000.0).round(1).to_s + "K" %>
	<%# elsif saved_count >= 1000 %>
		<%# saved_count_string = (saved_count/1000.0).round(2).to_s + "K" %>
	<%# elsif saved_count < 1000 %>
		<%# saved_count_string = saved_count.to_s %>
	<%# end %>
<%# end %>

<% if user_signed_in? %>
  <% unless current_user.saved_events.pluck(:event_id).include? event.id %>
    <%= form_for(current_user.saved_events.build, remote: true) do |f| %>
      <div><%= hidden_field_tag :event_id, event.id %></div>
      <%#= f.button "Save&nbsp;<span class=\"thin-count\">#{saved_count_string}</span>".html_safe(), class: "btn btn-default btn-default-primary-text btn-add-remove-calendar" %>
      <%= f.button "Save".html_safe(), class: "btn btn-default btn-default-primary-text btn-add-remove-calendar" %>
    <% end %>
  <% else %>
    <%= link_to '<span class="added-to-calendar"></span>'.html_safe, saved_event_path(event.id), remote: true, rel: "nofollow", method: :delete, class: "btn btn-default btn-default-burnt-orange-text btn-add-remove-calendar btn-remove-from-calendar" %>
  <% end %>
<% else %>
  <%#= link_to "Save&nbsp;<span class=\"thin-count\">#{saved_count_string}</span>".html_safe(), saved_events_path, method: :post, rel: "nofollow", class: "btn btn-default btn-add-remove-calendar btn-default-primary-text" %>
  <%= link_to "Save".html_safe(), saved_events_path, method: :post, rel: "nofollow", class: "btn btn-default btn-add-remove-calendar btn-default-primary-text" %>
<% end %>
<span><%= link_to("Edit event", edit_event_path(event), class: "edit-event-link", title: "Only you the sharer can see this option to edit. Click to proceed.", data: { toggle: "tooltip", placement: "bottom" } ) if event.user == current_user %></span>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>