config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'events#index' 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  resources :users, only: [:show]
  resources :contact_forms, only: [:create]
  resources :contact_organizers, only: [:create, :new]
  resources :report_issues, only: [:create, :new]
  resources :email_events, only: [:create, :new]
  resources :report_events, only: [:create, :new]
  resources :shared_events, only: [:index]
  resources :events
  resources :saved_events, only: [:create, :destroy, :index]
  get 'contact_us', to: 'contact_forms#new'
  get 'autocomplete', to: 'events#autocomplete'
  get 'howitworks' => 'static_pages#howitworks'
  get 'terms' => 'static_pages#terms'
end

app/models/event.rb
class Event < ActiveRecord::Base
  is_impressionable
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]
  
  before_save :set_descriptiontext
  include Searchable
  attachment :poster, type: :image
  validate :file_content_type?
  belongs_to :user
  belongs_to :event_category
  belongs_to :location
  has_many :saved_events, dependent: :destroy
  has_many :event_times, dependent: :destroy
  has_many :event_schedules, dependent: :destroy
  accepts_nested_attributes_for :event_schedules, :reject_if => :all_blank, :allow_destroy => true
  has_many :tickets, dependent: :destroy
  accepts_nested_attributes_for :tickets, :reject_if => :all_blank, :allow_destroy => true
  validates :title, uniqueness: { scope: :venue, conditions: -> { where("created_at > ?", 1.month.ago) }, message: " - Duplicate warning. An event with the same title and venue was created within the last month. Contact us if your event is different." }
  # validates :title, uniqueness: { scope: :venue }
  # validates :title, uniqueness: true
  validates :event_category_id, presence: true
  validates :location_id, presence: true
  validates :title, presence: true
  validates :title, length: { maximum: 80 }
  validates :event_schedules, presence: { message: "can't be blank, at least one event time is required" }
  validates :venue, presence: true
  validates :venue, length: { maximum: 200 }
  validates :entry, presence: true
  validates :poster, presence: true
  validates :description, presence: true, length: { minimum: 50 }
  validates :confirm_truth, acceptance: true
  validates :entry,
    :inclusion  => { :in => [ 'Free', 'Paid'],
    :message    => "%{value} is not a valid entry value" }
  before_validation { self.tickets.clear if self.entry == "Free" }
  # this reindexes the corresponding document in ElasticSearch when an event's event type changes
  after_update { __elasticsearch__.index_document if self.event_category_id_changed? }
  after_update { __elasticsearch__.index_document if self.location_id_changed? }

  after_commit on: [:create] do
    __elasticsearch__.index_document
  end

  after_commit on: [:update] do
    __elasticsearch__.update_document
  end

  after_commit on: [:destroy] do
    __elasticsearch__.delete_document
  end

  # takes care of instances where event is touched and document is created before a rollback happens
  # after_rollback { __elasticsearch__.try(:delete_document) }

  # this takes care of reindexing if ticket or time details change
  after_touch { __elasticsearch__.index_document }

  def set_descriptiontext
    self.descriptiontext = Nokogiri::HTML(self.description.gsub(/<p>|<ul>|<ol>|<li>/, ' ')).text.squish if self.description_changed?
  end

  def png?(data)
    pre_characters = data[0,4].force_encoding('UTF-8') 
    return pre_characters == "\x89PNG"
  end

  def gif?(data)
    pre_characters = data[0,4].force_encoding('UTF-8') 
    return pre_characters == "GIF8"
  end

  def jpeg?(data)
    pre_characters = data[0,2].force_encoding('UTF-8')
    return pre_characters == "\xFF\xD8"
  end

  def file_is_image?
    f = poster.to_io
    data = f.read(9) # magic numbers are up to 9 bytes
    f.close
    return png?(data) || gif?(data) || jpeg?(data)
  end

  def file_content_type?
    if self.poster.present? && !file_is_image?
      self.errors.add(:poster, "should be PNG, JPEG or GIF file type")
    end
  end

  # It returns the articles whose titles contain one or more words that form the query
  def self.shared_search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("LOWER(title) like ?", "%#{query}%".downcase)
  end

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :title,
      [:title, :venue]
    ]
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  after_filter :store_location, only: [:show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index, :autocomplete]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_cache_buster, only: [:show, :index]
  impressionist :actions => [:show], :unique => [:session_hash]
  

  # GET /events
  # GET /events.json
  def index

    # enable this if lots of events are added in many counties
    # hmm doesnt work with clear filters
    # params[:l] ||= current_user.location.name if user_signed_in?

    options = {
      event_category_name: params[:e],
      from: params[:f],
      to: params[:t],
      date: params[:d],
      entry: params[:n],
      location: params[:l],
      lat: params[:lat],
      lng: params[:lng],
      km: params[:km],
      upcoming_ongoing: params[:uo]
    }

    ongoing_options = {
      event_category_name: params[:e],
      from: params[:f],
      to: params[:t],
      date: params[:d],
      entry: params[:n],
      location: params[:l],
      lat: params[:lat],
      lng: params[:lng],
      km: params[:km],
      upcoming_ongoing: "ongoing"
    }

    @events = Event.search(params[:q], options).page(params[:page]).per_page(10)

    # if params[:uo] == "ongoing"
    #   event_responses = @events.results.response.each

    #   @total_ongoing_events = 0

    #   event_responses.each do |event_response|
    #     ongoing_event_time = event_response.event_times.select { |event_time| event_time.starts < Time.zone.now && event_time.ends > Time.zone.now }
    #     if ongoing_event_time.count > 0
    #       @total_ongoing_events += 1
    #     end
    #   end
    # else
    #   @ongoing_events = Event.search(params[:q], ongoing_options)

    #   event_responses = @ongoing_events.results.response.each

    #   @total_ongoing_events = 0

    #   event_responses.each do |event_response|
    #     ongoing_event_time = event_response.event_times.select { |event_time| event_time.starts < Time.zone.now && event_time.ends > Time.zone.now }
    #     if ongoing_event_time.count > 0
    #       @total_ongoing_events += 1
    #     end
    #   end
    # end

    if params[:uo] == "ongoing"
      # event_responses = @events.results.response.each

      @total_ongoing_events = @events.count

      # event_responses.each do |event_response|
      #   ongoing_event_time = event_response.event_times.select { |event_time| event_time.starts < Time.zone.now && event_time.ends > Time.zone.now }
      #   if ongoing_event_time.count > 0
      #     @total_ongoing_events += 1
      #   end
      # end
    else
      @ongoing_events = Event.search(params[:q], ongoing_options)
      @total_ongoing_events = @ongoing_events.count

    end

    # passing a specific set of predetermined params to aggregation links to avoid Cross Site Scripting vulnerability
    @clean_params = { 
      q: params[:q], 
      e: params[:e], 
      f: params[:f], 
      t: params[:t], 
      d: params[:d], 
      n: params[:n], 
      l: params[:l], 
      lat: params[:lat], 
      lng: params[:lng], 
      km: params[:km], 
      uo: params[:uo] 
    }

    set_meta_tags og: {
      title: "FunJaza - Find & Share Fun Events",
      description: "Find fun events happening across Kenya. And if you're planning one, share it for free!",
      image: "#{root_url}images/funjaza_logo_and_pacifico_tag_1200_1200.jpg"
    }
    set_meta_tags twitter: {
      card: "summary_large_image",
      title: "FunJaza - Find & Share Fun Events",
      description: "Find fun events happening across Kenya. And if you're planning one, share it for free!",
      image: "#{root_url}images/funjaza_logo_and_pacifico_tag_1200_1200.jpg"
    }

    respond_to do |format|
      format.html
      format.js
    end

  end

  # GET /events/1
  # GET /events/1.json
  def show
    impressionist(@event)
    set_meta_tags og: {
      title: @event.title,
      description: @event.descriptiontext
    }
    set_meta_tags twitter: {
      card: "summary_large_image",
      title: @event.title,
      description: @event.descriptiontext
    }
  end

  # GET /events/new
  def new
    @event = Event.new
    # @event_new = true
    @event.event_schedules.build unless @event.event_schedules.any?
    @event.tickets.build unless @event.tickets.any?
  end

  # GET /events/1/edit
  def edit
    # @event.event_times.build unless @event.event_times.any?
    @event.event_schedules.build unless @event.event_schedules.any?
    @event.tickets.build unless @event.tickets.any?
  end

  # POST /events
  # POST /events.json
  def create

    # begin
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    # begin
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def autocomplete
    options = {
      event_category_name: params[:e],
      from: params[:f],
      to: params[:t],
      date: params[:d],
      entry: params[:n],
      location: params[:l],
      lat: params[:lat],
      lng: params[:lng],
      km: params[:km],
      upcoming_ongoing: params[:uo]
    } 

    render json: Event.autocomplete(params[:term], options).map { |e| 
      [
        e.slug,
        e.title,
        (e.event_category.name).titleize,
        e.venue,
        if e.event_times.count == 1 
          e.event_times[0].starts_string
        else
          "#{e.event_times[0].starts_string} + more times"
        end,
        e.try(:highlight).try('descriptiontext.autocomplete').try(:join)
      ]
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, 
                                    :description, 
                                    :user_id, 
                                    :event_category_id, 
                                    :venue,
                                    :location_id,
                                    :entry, 
                                    :point,
                                    :poster,
                                    :remove_poster,
                                    :confirm_truth,
                                    # event_times_attributes: [:id, :starts_date, :starts_time, :ends_date, :ends_time, :repeats, :_destroy],
                                    event_schedules_attributes: [:id, :starts_date, :starts_time, :ends_date, :ends_time, :schedule, :until, :_destroy],
                                    tickets_attributes: [:id, :name, :price, :_destroy])
    end

    def correct_user
      @event = Event.friendly.find(params[:id])
      redirect_to root_url unless @event.user == current_user
    end

    def set_cache_buster
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 05 Oct 1984 00:00:00 GMT"
    end

    def store_location
      # store last url - this is needed for post-login redirect to whatever the user last visited.
      return unless request.get? 
      if (request.path != "/users/sign_in" &&
          request.path != "/users/sign_up" &&
          request.path != "/users/password/new" &&
          request.path != "/users/password/edit" &&
          request.path != "/users/confirmation" &&
          request.path != "/users/sign_out" &&
          !request.xhr?) # don't store ajax calls
        session[:previous_url] = request.fullpath 
      end
    end

end

app/helpers/events_helper.rb
module EventsHelper
	def number_to_currency_custom(number)
		number_to_currency(number, unit: "KSh")
	end

	def cache_key_for_events
		count          = Event.count
    max_updated_at = Event.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "events/all-#{count}-#{max_updated_at}"
  end
end

app/views/events/_aggsLocationList.html.erb
<% location_buckets = @events.results.response.response['aggregations']['locations']['filtered_locations']['buckets'].sort_by { |l| [-l[1].doc_count, l[0]] } %>

<% if params[:l] %>
	<li class="agg-list-item"><%= link_to "All", events_path(@clean_params.merge(l: nil)), remote: true, rel: "nofollow" %></li>
<% end %>	
<% location_buckets.each do |l| %>
	<% if params[:l] != l[0] %>
		<%=
		  content_tag :li, (link_to events_path(@clean_params.merge(l: l[0])), remote: true, rel: "nofollow" do
        l[0].titleize.html_safe + " " + content_tag(:small, "#{l[1]['doc_count']}", class: "agg-count").html_safe
		  end), class: "agg-list-item"
		%>
	<% end %>
	<% if params[:l] == l[0] %>
		<%=
		  content_tag :li, (link_to events_path(@clean_params.merge(l: nil)), remote: true, rel: "nofollow" do
        l[0].titleize.html_safe + " " + content_tag(:small, "#{l[1]['doc_count']}", class: "agg-count").html_safe
		  end), class: "agg-list-item active"
		%>
	<% end %>
<% end %>

app/views/events/show.html.erb
<% title @event.title %>
<% description @event.descriptiontext %>
<% set_meta_tags twitter: {
                 image: "https://www.funjaza.co.ke#{attachment_url(@event, :poster)}" } %>
<% set_meta_tags og: {
                 image: "https://www.funjaza.co.ke#{attachment_url(@event, :poster)}" } %>

<% unless @event.is_active == false %>

  <% ongoing_event_times = [] %>
  <% upcoming_event_times = [] %>
  <% past_event_times = [] %>
  <% @event.event_times.each do |event_time| %>
    <% ongoing_event_times << event_time if event_time.starts < Time.zone.now && event_time.ends > Time.zone.now %>
    <% upcoming_event_times << event_time if event_time.starts > Time.zone.now %>
    <% past_event_times << event_time if event_time.starts < Time.zone.now && event_time.ends < Time.zone.now %>
  <% end %>
  <% upcoming_event_times.sort_by! { |t| t.starts} %>
  <% past_event_times.sort_by! { |t| t.starts} %>



  <div class="row event-show-image_and_details">
    <div class="col-sm-6 col-lg-4">

      <div class="event-title-show-wrapper visible-xs-block">
        <h3 class="event-title-show"><%= @event.title %></h3>
        <!-- <span class="grayed-out"><%#= link_to @event.user.name, user_path(@event.user.slug) %></span> -->
        <span class="grayed-out">Shared by <%= @event.user.name %>&nbsp;<small>(<%= pluralize(@event.user.events.count, 'share') %>)</small>&nbsp;&nbsp;<span class="brand-fun">|</span>&nbsp;&nbsp;Last updated on <%= @event.updated_at.strftime("%d %b %Y") %>&nbsp;&nbsp;<span class="brand-fun">|</span>&nbsp;&nbsp;<%= pluralize(@event.impressionist_count(:filter => :session_hash), 'view') %></span>
      </div>

      <div class="event-img-show-wrapper">
        <%= attachment_image_tag(@event, :poster, :fit, 340, 510, fallback: "missing_event_show_sm_to_lg.jpg", class: "event-img event-img-show hidden-xs", alt: "Event poster image") %>
        <%= attachment_image_tag(@event, :poster, :fit, 280, 420, fallback: "missing_event_show_xs.jpg", class: "event-img event-img-show visible-xs-inline", alt: "Event poster image") %>
      </div>

      <div class="save-social-btns-wrapper">

        <div class="fb-btn-wrapper">
          <a href="http://www.facebook.com/sharer.php?u=<%= request.original_url %>" title="Share event on Facebook" target="_blank" class="btn btn-facebook" rel="nofollow"><i class="fa fa-facebook"></i> Share</a>
        </div>

        <div class="twitter-btn-wrapper">
          <a href="https://twitter.com/intent/tweet?text=Check out '<%= @event.title %>'&url=<%= request.original_url %>&via=FunJaza" title="Share event on Twitter" target="_blank" class="btn btn-twitter" rel="nofollow"><i class="fa fa-twitter"></i> Tweet</a>
        </div>

        </br>

        <div class="email-btn-wrapper">
          <%= link_to '<i class="fa fa-envelope-o"></i> Email'.html_safe, new_email_event_path(id: @event.slug), remote: true, rel: "nofollow", class: "btn btn-default btn-default-primary-text email-share-button", data: { toggle: "modal", target: "#myModal" }, title: "Email event to a friend" %>
        </div>

        <div class="save-btn-wrapper">
          <!-- start: event save button -->
          <div class="calendar_button" id="calendar_button_<%= @event.id %>">
            <%= render partial: 'shared/calendar_buttons', locals: { event: @event } %>
          </div>
          <!-- end: event save button -->
        </div>
        
      </div>
    </div>

    <div class="col-sm-6 col-lg-8 event-details-show-wrapper">
      <div class="event-title-show-wrapper hidden-xs">
        <h3 class="event-title-show"><%= @event.title %></h3>
         <span class="grayed-out">Shared by <%= @event.user.name %>&nbsp;<small>(<%= pluralize(@event.user.events.count, 'share') %>)</small>&nbsp;&nbsp;<span class="brand-fun">|</span>&nbsp;&nbsp;Last updated on <%= @event.updated_at.strftime("%d %b %Y") %>&nbsp;&nbsp;<span class="brand-fun">|</span>&nbsp;&nbsp;<%= pluralize(@event.impressionist_count(:filter => :session_hash), 'view') %></span>
      </div>

      <p>
        <%= @event.event_category.name.titleize %>
      </p>

      <% if ongoing_event_times.any? && upcoming_event_times.any? %>
        <% ongoing_event_times.each do |ongoing_event_time| %>
          <%= "<p>Ongoing till #{ongoing_event_time.ends.to_datetime.strftime("%l:%M%P")} today.</p>".html_safe if ongoing_event_time.ends.to_date == Time.zone.now.to_date %>
          <%= "<p>Ongoing till #{ongoing_event_time.ends.to_datetime.strftime("%l:%M%P")} tomorrow.</p>".html_safe if ongoing_event_time.ends.to_date == Time.zone.now.to_date + 1.day %>
        <% end %>
        <div class="event-detail-more-dates-show">
          <%= link_to "show more times", "#upcoming_event_times", data: { toggle: "collapse" }, class: "more-times-available-link" %><span><small> (upto next 100)</small></span>
          <ul id="upcoming_event_times" class="collapse next-future-dates">
          <% upcoming_event_times.first(100).each do |t| %>
            <li>
              <% if t.starts.to_date == t.ends.to_date %>
                <%= t.starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span> <%= t.ends.to_datetime.strftime("%l:%M%P") %>
              <% else %>
                <%= t.starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span> <%= t.ends.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %>
              <% end %>
            </li>
          <% end %>
          </ul>
        </div>
      <% elsif ongoing_event_times.any? && upcoming_event_times.empty? %>
        <% ongoing_event_times.each do |ongoing_event_time| %>
          <%= "<p>Ongoing till #{ongoing_event_time.ends.to_datetime.strftime("%l:%M%P")} today.</p>".html_safe if ongoing_event_time.ends.to_date == Time.zone.now.to_date %>
          <%= "<p>Ongoing till #{ongoing_event_time.ends.to_datetime.strftime("%l:%M%P")} tomorrow</p>".html_safe if ongoing_event_time.ends.to_date == Time.zone.now.to_date + 1.day %>
        <% end %>
      <% elsif ongoing_event_times.empty? && upcoming_event_times.any? %>
        <p>
          <% if upcoming_event_times[0].starts.to_date == upcoming_event_times[0].ends.to_date %>
            <%= upcoming_event_times[0].starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span> <%= upcoming_event_times[0].ends.to_datetime.strftime("%l:%M%P") %>
          <% else %>
            <%= upcoming_event_times[0].starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span>  <%= upcoming_event_times[0].ends.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %>
          <% end %>
        </p>
        <% future_upcoming_event_times = upcoming_event_times.drop(1) %>
        <% if future_upcoming_event_times.any? %>
          <div class="event-detail-more-dates-show">
            <%= link_to "show more times", "#future_upcoming_event_times", data: { toggle: "collapse" }, class: "more-times-available-link" %><span><small> (upto next 100)</small></span>
            <ul id="future_upcoming_event_times" class="collapse next-future-dates">
            <% future_upcoming_event_times.first(100).each do |t| %>
              <li>
                <% if t.starts.to_date == t.ends.to_date %>
                  <%= t.starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span> <%= t.ends.to_datetime.strftime("%l:%M%P") %>
                <% else %>
                  <%= t.starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span> <%= t.ends.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        <% end %>
      <% elsif ongoing_event_times.empty? && upcoming_event_times.empty? && past_event_times.any? %>
        <p class="text-danger">NB: This event occurred in the past.</p>
        <p>
          <% if past_event_times[0].starts.to_date == past_event_times[0].ends.to_date %>
            <%= past_event_times[0].starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span> <%= past_event_times[0].ends.to_datetime.strftime("%l:%M%P") %>
          <% else %>
            <%= past_event_times[0].starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span>  <%= past_event_times[0].ends.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %>
          <% end %>
        </p>
        <% more_past_event_times = past_event_times.drop(1) %>
        <% if more_past_event_times.any? %>
          <div class="event-detail-more-dates-show">
            <%= link_to "show more times", "#more_past_event_times", data: { toggle: "collapse" }, class: "more-times-available-link" %><span><small> (upto next 100)</small></span>
            <ul id="more_past_event_times" class="collapse next-future-dates">
            <% more_past_event_times.first(100).each do |t| %>
              <li>
                <% if t.starts.to_date == t.ends.to_date %>
                  <%= t.starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span> <%= t.ends.to_datetime.strftime("%l:%M%P") %>
                <% else %>
                  <%= t.starts.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %> <span>-</span> <%= t.ends.to_datetime.strftime("%a, %d %b %Y, %l:%M%P") %>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>

      <% tickets = @event.tickets %>
      <% sorted_tickets = tickets.sort_by { | ticket | ticket[:price].to_f } %>
      <% if tickets.empty? && @event.entry == "Free" %>
        <p><span class="brand-fun">Free</span></p>
      <% elsif tickets.empty? && @event.entry == "Paid" %>
        <p>Paid <span class="grayed-out"><small>(ticket details not provided)</small></span></p>
      <% elsif !tickets.empty? && @event.entry == "Paid" %>
        <ul class="event-tickets-list">
          <% ticket_count = 0 %>
          <% sorted_tickets.each do |ticket| %>
            <% ticket_count += 1 %>
            <% if ticket.price == 0  %>
              <li><%= ticket.name %> - Free</li>
            <% else %>
              <li><%= ticket.name %> - <%= number_to_currency_custom(ticket.price) %></li>
            <% end %>
            <li><%= '<span class="brand-fun">|</span>'.html_safe unless ticket_count == @event.tickets.count %></li>
          <% end %>
        </ul>
      <% end %>

      <p>
        <%= @event.venue %>
      </p>

      <% if @event.point.present? %>
        <p>
          <a id="show-hide-map-link" data-toggle="collapse" href="#map-container-show" aria-expanded="false" aria-controls="map-container-show">show map</a>
        </p>
      <% end %>

      <% if @event.point.present? %>
        <div class="collapse" id="map-container-show">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe
              frameborder="0" style="border:0"
              class="embed-responsive-item"
              src="https://www.google.com/maps/embed/v1/search?key=AIzaSyCkAtOHwdyey36VyyAOx_UV0KcgYsWXmTE&q=<%= @event.venue.gsub(/\s/, '+').gsub("&", "") %>">
            </iframe>
          </div>
        </div>
        
      <% end %>

      <% if @event.description.present? %>
        <div class="panel panel-default">
          <div class="panel-heading">Details</div>
          <div class="panel-body">
            <%= sanitize @event.description %>
          </div>
        </div>
      <% end %>

      <p class="report-event-link"><span class="text-danger">* </span><small><span class="grayed-out">Is this event fake, offensive, incorrect or a duplicate?</span> <%= link_to "Report", new_report_event_path(id: @event.slug), rel: "nofollow", remote: true, data: { toggle: "modal", target: "#myModal-report-event" } %></small></p>
    </div>
  </div>

  <hr>

  <div class="ads-wrapper">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Ad on event show page -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-7006896596009658"
         data-ad-slot="9064033326"
         data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  </div>

  <div class="modal fade" id="myModal-report-event" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  </div>
<% else %>
    <div class="event-details-show-wrapper">
      <div class="event-title-show-wrapper">
        <h3 class="event-title-show"><%= @event.title %></h3>
         <span class="grayed-out">Shared by <%= @event.user.name %>&nbsp;<small>(<%= pluralize(@event.user.events.count, 'share') %>)</small>&nbsp;&nbsp;<span class="brand-fun">|</span>&nbsp;&nbsp;Last updated on <%= @event.updated_at.strftime("%d %b %Y") %>&nbsp;&nbsp;<span class="brand-fun">|</span>&nbsp;&nbsp;<%= pluralize(@event.impressionist_count(:filter => :session_hash), 'view') %></span>
      </div>
      <p class="brand-fun">Sorry, this event's details will remain hidden until necessary corrections are made by the sharer.</p>
    </div>
<% end %>